#include "adc_monitor.h"
#include "FreeRTOS.h"
#include "task.h"
#include "event_groups.h"
#include "stm32g4xx_hal.h"

/* ADC handle generated by CubeMX */
extern ADC_HandleTypeDef hadc1;

/* Fault event group - shared with fault manager task */
EventGroupHandle_t fault_event_group;

/* Fault bit definitions */
#define FAULT_BIT_OVERCURRENT    (1 << 0)
#define FAULT_BIT_STALL          (1 << 1)
#define FAULT_BIT_UNDERVOLTAGE   (1 << 2)

/* Overcurrent threshold - ADC counts corresponding to max safe current
   ESC1 shunt resistor converts current to voltage, ADC reads voltage
   Tune this value based on measured shunt resistor and ADC calibration */
#define OVERCURRENT_THRESHOLD_ADC    3500

/* ADC monitor task - samples phase current every 10ms */
void adc_monitor_task(void *args) {
    fault_event_group = xEventGroupCreate();
    uint32_t adc_value = 0;

    while (1) {
        /* Start ADC conversion */
        HAL_ADC_Start(&hadc1);

        /* Wait for conversion to complete - 10ms timeout */
        if (HAL_ADC_PollForConversion(&hadc1, 10) == HAL_OK) {
            adc_value = HAL_ADC_GetValue(&hadc1);

            /* Check overcurrent threshold */
            if (adc_value > OVERCURRENT_THRESHOLD_ADC) {
                xEventGroupSetBits(fault_event_group, FAULT_BIT_OVERCURRENT);
            }
        }

        HAL_ADC_Stop(&hadc1);

        /* Sample every 10ms */
        vTaskDelay(pdMS_TO_TICKS(10));
    }
}
