#include "can_telemetry.h"
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "stm32g4xx_hal.h"
#include "velocity_control.h"

/* FDCAN handle generated by CubeMX */
extern FDCAN_HandleTypeDef hfdcan1;

/* Queue for passing setpoints from CAN task to velocity task */
QueueHandle_t setpoint_queue;

/* CAN message IDs */
#define CAN_ID_TELEMETRY    0x100  /* outgoing motor state */
#define CAN_ID_SETPOINT     0x101  /* incoming velocity setpoint */

/* Telemetry send interval */
#define TELEMETRY_INTERVAL_MS    50

/* Initialize FDCAN peripheral and start it */
static HAL_StatusTypeDef can_start(void) {
    FDCAN_FilterTypeDef filter = {0};

    /* Accept only setpoint message ID */
    filter.IdType       = FDCAN_STANDARD_ID;
    filter.FilterIndex  = 0;
    filter.FilterType   = FDCAN_FILTER_MASK;
    filter.FilterConfig = FDCAN_FILTER_TO_RXFIFO0;
    filter.FilterID1    = CAN_ID_SETPOINT;
    filter.FilterID2    = 0x7FF;

    if (HAL_FDCAN_ConfigFilter(&hfdcan1, &filter) != HAL_OK) return HAL_ERROR;
    if (HAL_FDCAN_Start(&hfdcan1) != HAL_OK) return HAL_ERROR;
    if (HAL_FDCAN_ActivateNotification(&hfdcan1,
        FDCAN_IT_RX_FIFO0_NEW_MESSAGE, 0) != HAL_OK) return HAL_ERROR;

    return HAL_OK;
}

/* Transmit motor telemetry frame */
static void can_send_telemetry(float rpm, uint8_t fault_active) {
    FDCAN_TxHeaderTypeDef tx_header = {0};
    uint8_t tx_data[8] = {0};

    tx_header.Identifier          = CAN_ID_TELEMETRY;
    tx_header.IdType              = FDCAN_STANDARD_ID;
    tx_header.TxFrameType         = FDCAN_DATA_FRAME;
    tx_header.DataLength          = FDCAN_DLC_BYTES_8;
    tx_header.ErrorStateIndicator = FDCAN_ESI_ACTIVE;
    tx_header.BitRateSwitch       = FDCAN_BRS_OFF;
    tx_header.FDFormat            = FDCAN_CLASSIC_CAN;
    tx_header.TxEventFifoControl  = FDCAN_NO_TX_EVENTS;
    tx_header.MessageMarker       = 0;

    /* Pack RPM as 16-bit fixed point in bytes 0-1
       fault status in byte 2 */
    uint16_t rpm_fixed = (uint16_t)(rpm * 10.0f);
    tx_data[0] = (rpm_fixed >> 8) & 0xFF;
    tx_data[1] = rpm_fixed & 0xFF;
    tx_data[2] = fault_active;

    HAL_FDCAN_AddMessageToTxFifoQ(&hfdcan1, &tx_header, tx_data);
}

/* CAN telemetry task - lowest priority, runs when nothing else needs CPU */
void can_telemetry_task(void *args) {
    setpoint_queue = xQueueCreate(4, sizeof(float));
    float setpoint = 0.0f;

    can_start();

    while (1) {
        /* Check for incoming setpoint command */
        FDCAN_RxHeaderTypeDef rx_header;
        uint8_t rx_data[8] = {0};

        if (HAL_FDCAN_GetRxMessage(&hfdcan1, FDCAN_RX_FIFO0,
                                    &rx_header, rx_data) == HAL_OK) {
            if (rx_header.Identifier == CAN_ID_SETPOINT) {
                /* Unpack setpoint RPM from bytes 0-1 */
                uint16_t rpm_fixed = ((uint16_t)rx_data[0] << 8) | rx_data[1];
                setpoint = (float)rpm_fixed / 10.0f;

                /* Send to velocity task via queue - non-blocking */
                xQueueOverwrite(setpoint_queue, &setpoint);
                velocity_set_target(setpoint);
            }
        }

        /* Send telemetry every 50ms */
        can_send_telemetry(velocity_get_actual(), 0);
        vTaskDelay(pdMS_TO_TICKS(TELEMETRY_INTERVAL_MS));
    }
}
